#!/usr/bin/env php
<?php

if (!getenv('YII_ENV')) {
    $dotenv = new Dotenv\Dotenv(__DIR__ . 'environments/default/');
    $dotenv->load();
}

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'default');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/common/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
