#microservice-memcached:
#  image: phpdockerio/memcached:latest
#  container_name: microservice-memcached
#
#microservice-redis:
#  image: redis
#  container_name: microservice-redis
#  volumes:
#      - ./redis/data:/data
#
#microservice-mongo:
#  image: mongo
#  container_name: microservice-mongo
#  volumes:
#      - ./mongo/data:/data/db
#
#microservice-rabbit:
#  image: rabbitmq
#  container_name: microservice-rabbit
#
#microservice-mailhog:
#  image: phpdockerio/mailhog:latest
#  container_name: microservice-mailhog
#  ports:
#    - "8102:8025"
#
microservice-mysql:
  image: mysql
  container_name: microservice-mysql
  env_file:
    - db.env
  volumes:
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql

microservice-webserver:
  image: xdrum/nginx-extras
  container_name: microservice-webserver
  volumes:
      - ../../../:/var/www/microservice
      - ./nginx/nginx.conf:/etc/nginx/sites-enabled/default
  ports:
   - "8101:80"
  links:
   - microservice-php-fpm

#microservice-sphinx:
#  build: sphinx/
#  dockerfile: Dockerfile
#  container_name: microservice-sphinx
#  expose:
#    - "3312"
#    - "3320"
#  volumes:
#    - ./sphinx/index:/sphinx-index
#    - ./sphinx/conf/sphinx.conf:/sphinx-conf/sphinx.conf
#
microservice-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: microservice-php-fpm
  volumes:
    - ../../../:/var/www/microservice
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
  env_file:
    - yii2.env

  links:
#    - microservice-memcached
#    - microservice-mailhog
    - microservice-mysql
#    - microservice-sphinx
#    - microservice-redis
#    - microservice-mongo
#    - microservice-rabbit
